"""add user_id to stories

Revision ID: 22f779b8b933
Revises: 6e00b9facdba
Create Date: 2026-03-28 20:29:02.997409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22f779b8b933'
down_revision: Union[str, Sequence[str], None] = '6e00b9facdba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'stories', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stories', type_='foreignkey')
    op.drop_column('stories', 'user_id')
    # ### end Alembic commands ###
