"""add user tables

Revision ID: 6e00b9facdba
Revises: 94692fa453e2
Create Date: 2026-03-28 20:23:11.352116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e00b9facdba'
down_revision: Union[str, Sequence[str], None] = '94692fa453e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('avatar', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'BANNED', name='userstatus'), nullable=True),
    sa.Column('is_guest', sa.Boolean(), nullable=True),
    sa.Column('free_generations_today', sa.Integer(), nullable=True),
    sa.Column('last_reset_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('guest_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('guest_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('data_snapshot', sa.JSON(), nullable=True),
    sa.Column('merged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guest_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guest_mappings')
    op.drop_table('users')
    # ### end Alembic commands ###
