"""add shares table

Revision ID: 827f43e4658e
Revises: cf6518a6b120
Create Date: 2026-03-29 16:12:39.180618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '827f43e4658e'
down_revision: Union[str, Sequence[str], None] = 'cf6518a6b120'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_preference_user_tag'), table_name='preferences')
    op.drop_index(op.f('idx_preference_user_world'), table_name='preferences')
    op.drop_table('preferences')
    op.drop_constraint(op.f('fk_stories_user_id'), 'stories', type_='foreignkey')
    op.create_foreign_key(None, 'stories', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stories', type_='foreignkey')
    op.create_foreign_key(op.f('fk_stories_user_id'), 'stories', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_table('preferences',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('world_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('story_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('tag', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], name=op.f('preferences_story_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('preferences_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('preferences_pkey'))
    )
    op.create_index(op.f('idx_preference_user_world'), 'preferences', ['user_id', 'world_id'], unique=False)
    op.create_index(op.f('idx_preference_user_tag'), 'preferences', ['user_id', 'tag'], unique=False)
    # ### end Alembic commands ###
